// src/constants/strings.js

export const t = {
  dashboard: 'Home Dashboard', discussions: 'Group Discussions', portfolio: 'Portfolio', dinners: 'Events', community: 'Members', messages: 'Messages', profile: 'My Profile', clubAdmin: 'Club Admin',
  adminDashboard: 'Admin Dashboard', manageMembers: 'Members', manageDeals: 'Deals & Portfolio', manageDiscussions: 'Discussions', manageEvents: 'Events', communications: 'Communications', activityLog: 'Activity Log',
  ventureClub: 'Venture Club', kizunaClub: 'Kizuna Club', welcomeBack: 'Welcome back', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', add: 'Add', archive: 'Archive', publish: 'Publish', schedule: 'Schedule', send: 'Send', search: 'Search', back: 'Back', close: 'Close', confirm: 'Confirm', actions: 'Actions', status: 'Status', date: 'Date',
  totalMembers: 'Total Members', activeDeals: 'Active Deals', upcomingEvents: 'Upcoming Events', avgEngagement: 'Avg Engagement',
  addMember: 'Add Member', editMember: 'Edit Member', memberDetails: 'Member Details', lastLogin: 'Last Login', dealsViewed: 'Deals Viewed', sessionsAttended: 'Sessions Attended', sendEmail: 'Send Email',
  addDeal: 'Add Deal', editDeal: 'Edit Deal', fundHoldings: 'Fund Holdings', syndicationDeals: 'Syndication Deals', archivedDeals: 'Archived Deals', uploadDocument: 'Upload Document', coInvestors: 'Co-Investors',
  addDiscussion: 'Add Discussion', editDiscussion: 'Edit Discussion', viewRsvps: 'View RSVPs', sendReminder: 'Send Reminder', rsvpList: 'RSVP List', attending: 'Attending', notResponded: 'Not Responded',
  addEvent: 'Add Event', editEvent: 'Edit Event', attendeeList: 'Attendee List', capacity: 'Capacity',
  createAnnouncement: 'Create Announcement', bulkEmail: 'Bulk Email', scheduled: 'Scheduled', published: 'Published', draft: 'Draft', publishNow: 'Publish Now', scheduledFor: 'Scheduled for', emailAllMembers: 'Email All Members', subject: 'Subject', message: 'Message',
  allActivity: 'All Activity', filterByType: 'Filter by Type', memberAdded: 'Member added', memberEdited: 'Member edited', memberDeleted: 'Member deleted', dealAdded: 'Deal added', dealEdited: 'Deal edited', dealArchived: 'Deal archived', announcementPublished: 'Announcement published', emailSent: 'Email sent', eventCreated: 'Event created', discussionAdded: 'Discussion added', discussionDeleted: 'Discussion deleted',
  name: 'Name', email: 'Email', company: 'Company', title: 'Title', location: 'Location', interests: 'Interests', sector: 'Sector', stage: 'Stage', description: 'Description', venue: 'Venue', time: 'Time', topic: 'Topic', host: 'Host',
  recentActivity: 'Recent Activity', quickActions: 'Quick Actions', today: 'Today', tomorrow: 'Tomorrow', inDays: 'In {n} days', past: 'Past', active: 'Active', upcoming: 'Upcoming', members: 'members', confirmDelete: 'Are you sure you want to delete this?', noResults: 'No results found', reminderSent: 'Reminder sent successfully', emailSentSuccess: 'Email sent successfully', savedSuccessfully: 'Saved successfully', deletedSuccessfully: 'Deleted successfully', archivedSuccessfully: 'Archived successfully',
  nextDiscussion: 'Next Discussion', nextDinner: 'Next Dinner', portfolioOverview: 'Kizuna Fund 1 Portfolio', kizuna2026Fund: 'Kizuna 2026 Fund', clubLeadershipTeam: 'Club Leadership', viewDetails: 'View Details', joinZoom: 'Join Meeting', tokyoDinners: 'Tokyo Dinners', exclusiveGathering: 'Exclusive gathering for Kizuna Club members', attendees: 'Attendees', notAttending: 'Not Attending', memberDirectory: 'Member Directory', sendMessage: 'Send Message', viewProfile: 'View Profile', editProfile: 'Edit Profile', rsvp: 'RSVP', announcements: 'Announcements', pinned: 'Pinned', backToPortfolio: 'Back to Portfolio', backToDashboard: 'Back to Dashboard', more: 'More', investmentThesis: 'Investment Thesis', valuation: 'Valuation', growth: 'YoY Growth', ddComplete: 'DD Complete', to: 'To',
  adminLogin: 'Admin Login', password: 'Password', login: 'Login', logout: 'Logout', invalidPassword: 'Invalid password', memberView: 'Exit Admin', dealType: 'Deal Type', fund: 'Fund', syndication: 'Syndication', checkSize: 'Check Size', restore: 'Restore', restoredSuccessfully: 'Restored successfully', ddReports: 'DD Reports', dropPdfHere: 'Drop PDF here', ddReportAdded: 'DD report added', removeReport: 'Remove', saveChanges: 'Save Changes', unsavedChanges: 'Unsaved changes', changesSaved: 'All changes saved!', saving: 'Saving...', coinvestsWith: 'Co-invests with', bio: 'Bio', notableInvestments: 'Notable Investments', connectionStrength: 'Connection', viewAllCompanies: 'View All Companies', deployed: 'Deployed', attachFiles: 'Attach Files', attachedFiles: 'Attached Files', clubMembers: 'Club Members',
  alumniVentures: 'Alumni Ventures', clubMembersList: 'Club Members', addTeamMember: 'Add Leader', editTeamMember: 'Edit Team Member', linkedin: 'LinkedIn', phone: 'Phone', role: 'Role', teamMemberAdded: 'Team member added', teamMemberEdited: 'Team member edited', teamMemberDeleted: 'Team member deleted', downloadReport: 'Download', viewReport: 'View Report',
};

export const EN = t;
